# Generated by Django 5.2.1 on 2025-05-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_dealer',
            field=models.BooleanField(default=False),
        ),
    ]
