# Generated by Django 5.2.1 on 2025-07-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_driver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
