# Generated by Django 5.2.4 on 2025-08-02 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('contact_person', models.CharField(blank=True, max_length=30, null=True)),
                ('delivery_method', models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Ние вземаме')], default='delivery', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('responsible_logistic', models.ForeignKey(blank=True, limit_choices_to=models.Q(('is_logistics', True), ('is_logistics_manager', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_responsible', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
