# Generated by Django 5.2.4 on 2025-08-07 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Лице за контакт'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='delivery_method',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Ние вземаме')], default='delivery', max_length=20, verbose_name='Метод на доставка'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='responsible_logistic',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('groups__name', 'Logistics'), ('groups__name', 'Logistics Manager'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Отговорен логистик'),
        ),
    ]
