# Generated by Django 5.2.4 on 2025-08-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='vat_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ДДС номер'),
        ),
    ]
