# Generated by Django 5.2.4 on 2025-08-09 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_vat_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('supply', 'Доставка'), ('service', 'Услуга'), ('other', 'Друг')], default='supply', max_length=20, verbose_name='Тип')),
                ('signed_date', models.DateField(verbose_name='Дата на подписване')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Дата на изтичане')),
                ('file', models.FileField(upload_to='contracts/', verbose_name='Файл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier', verbose_name='Доставчик')),
            ],
        ),
    ]
