# Generated by Django 5.2.4 on 2025-08-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('supply', 'Стоки'), ('service', 'Услуги'), ('other', 'Други')], default='supply', max_length=20, verbose_name='Тип'),
        ),
    ]
