# Generated by Django 5.2.4 on 2025-08-11 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_alter_contract_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='delivery_method',
            field=models.CharField(choices=[('delivery', 'На място'), ('pickup', 'Вземане')], default='delivery', max_length=20, verbose_name='Метод на доставка'),
        ),
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday')], max_length=3)),
                ('time_slot', models.CharField(choices=[('08-10', '08:00-10:00'), ('10-12', '10:00-12:00'), ('12-14', '12:00-14:00'), ('14-16', '14:00-16:00')], max_length=5)),
                ('note', models.CharField(blank=True, max_length=150)),
                ('logistics_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_schedules', to='suppliers.supplier')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_schedules', to='suppliers.supplier')),
            ],
            options={
                'unique_together': {('day', 'time_slot', 'supplier')},
            },
        ),
    ]
