# Generated by Django 5.2.4 on 2025-08-13 10:35

import datetime

from django.db import migrations, models

# Generated by Django 5.2.4 on 2025-08-13 10:35



class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_alter_supplier_delivery_method_deliveryschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryschedule',
            name='hour',
            field=models.TimeField(default=datetime.time(8, 0)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='deliveryschedule',
            unique_together={('day', 'hour', 'supplier')},
        ),
        migrations.RemoveField(
            model_name='deliveryschedule',
            name='time_slot',
        ),
    ]
