# Generated by Django 5.2.4 on 2025-08-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_alter_deliveryschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryschedule',
            name='day',
            field=models.CharField(choices=[('mon', 'Понеделник'), ('tue', 'Вторник'), ('wed', 'Сряда'), ('thu', 'Четвъртък'), ('fri', 'Петък')], max_length=3),
        ),
    ]
