# Generated by Django 5.2.4 on 2025-08-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_alter_deliveryschedule_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryschedule',
            name='logistics_responsible',
        ),
    ]
