# Generated by Django 5.2.4 on 2025-08-13 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_remove_deliveryschedule_logistics_responsible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryschedule',
            options={'ordering': ['hour']},
        ),
        migrations.AlterUniqueTogether(
            name='deliveryschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='deliveryschedule',
            name='logistics_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryschedule',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryschedule',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='suppliers.supplier'),
        ),
        migrations.RemoveField(
            model_name='deliveryschedule',
            name='day',
        ),
    ]
