# Generated by Django 5.2.4 on 2025-08-14 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0010_alter_deliveryschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryschedule',
            name='date',
            field=models.DateField(default=datetime.date(2025, 8, 14)),
            preserve_default=False,
        ),
    ]
