# Generated by Django 5.1.6 on 2025-08-15 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0011_deliveryschedule_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('volume', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Обем (палети)')),
                ('thermolabile', models.BooleanField(default=False, verbose_name='Термолабилни')),
                ('narcotic', models.BooleanField(default=False, verbose_name='Наркотични')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Забележка')),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Drivers'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Шофьор')),
                ('supplier', models.ForeignKey(limit_choices_to={'delivery_method': 'pickup'}, on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
            options={
                'ordering': ['date', 'supplier'],
            },
        ),
    ]
