# Generated by Django 5.2.4 on 2025-08-17 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0012_pickupschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryschedule',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='deliveryschedule',
            name='hour',
            field=models.TimeField(verbose_name='Час на доставка'),
        ),
        migrations.AlterField(
            model_name='deliveryschedule',
            name='logistics_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Отговорен логистик'),
        ),
        migrations.AlterField(
            model_name='deliveryschedule',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Забележка'),
        ),
        migrations.AlterField(
            model_name='deliveryschedule',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='suppliers.supplier', verbose_name='Доставчик'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='delivery_method',
            field=models.CharField(choices=[('delivery', 'На място'), ('pickup', 'Вземане')], default='delivery', max_length=20, verbose_name='Тип доставка'),
        ),
    ]
