# Generated by Django 5.2.4 on 2025-08-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0013_alter_deliveryschedule_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='document_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вид документ'),
        ),
    ]
