# Generated by Django 5.2.4 on 2025-08-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0014_contract_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('supply', 'Стоки'), ('service', 'Услуги'), ('other', 'Други')], default='supply', max_length=20, verbose_name='Предмет на договора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='document_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Типове документи'),
        ),
    ]
