# Generated by Django 5.2.4 on 2025-08-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0015_alter_contract_contract_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='vat_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='ДДС номер'),
        ),
    ]
