# Generated by Django 5.2.1 on 2025-07-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('supplier', models.CharField(max_length=30, verbose_name='Доставчик')),
                ('location', models.CharField(max_length=30, verbose_name='Локация')),
                ('volume', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Обем')),
                ('thermolabile', models.BooleanField(verbose_name='Термолабилни')),
                ('narcotic', models.BooleanField(verbose_name='Наркотични')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Забележка')),
                ('driver', models.CharField(max_length=100, verbose_name='Към Транспорт')),
                ('received', models.BooleanField(default=False, verbose_name='Получено')),
            ],
        ),
    ]
