# Generated by Django 5.2.1 on 2025-07-21 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers_app', '0002_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='responsible_logistic',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('is_logistics', True), ('is_logistics_manager', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_responsible', to=settings.AUTH_USER_MODEL),
        ),
    ]
