# Generated by Django 5.2.1 on 2025-07-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers_app', '0003_alter_supplier_responsible_logistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='delivers_to_us',
        ),
        migrations.AddField(
            model_name='supplier',
            name='delivery_method',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Ние вземаме')], default='delivery', max_length=20),
        ),
    ]
