# Generated by Django 5.2.4 on 2025-08-14 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('suppliers', '0011_deliveryschedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, help_text='Допълнителна информация за поръчката', verbose_name='Бележка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(help_text='Изберете дата', verbose_name='Дата на поръчка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Изпратена'), ('confirmed', 'Потвърдена'), ('delivered', 'Доставена')], default='pending', help_text='Изберете статус на поръчката', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(help_text='Изберете доставчик', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='suppliers.supplier', verbose_name='Доставчик'),
        ),
    ]
