# Generated by Django 5.2.1 on 2025-07-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_externalwarehouse_delete_onsitedelivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalwarehouse',
            name='returnable',
        ),
        migrations.AlterField(
            model_name='externalwarehouse',
            name='driver',
            field=models.CharField(max_length=100, verbose_name='Подадено към транспорт'),
        ),
    ]
